format = """
[](fg:#6a708e)\
$time\
[](fg:#3b4056 bg:#525872)\
${custom.battery}\
[](fg:#525872 bg:#6a708e)\
$username\
$hostname\
[](fg:#6a708e bg:#6483c8)\
$directory\
[](fg:#6483c8 bg:#383e5a)\
$git_branch\
[](fg:#383e5a)\
\n\
$character
"""

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = "[  $time](fg:#c0caf5 bg:#3b4056)"

[custom.battery]
disabled = false
when = true
command = "~/.tool-bin/shell/bash/battery.sh"
format = "[ $output](bg:#525872)"

[username]
disabled = false
show_always = true
format = "[ $user](fg:#c0caf5 bg:#6a708e)"

[hostname]
disabled = false
ssh_only = false
format = "([@$hostname](fg:#c0caf5 bg:#6a708e))"

[directory]
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false
format = "[ $path](fg:#c0caf5 bg:#6483c8)"

[git_branch]
format = "([ $symbol$branch](fg:#7aa2f7 bg:#383e5a))"
